use_image: False
image_path: 'G:\Workspace\DS&Alg-Project1-Release\data\image'

use_pretrained_vgg16: True

make_prediction: False
test_images: 'G:\hp\Desktop\bird'

update_image_database: False
image_database_image_path: 'G:\Workspace\DS&Alg-Project1-Release\data\image'

find_similar_internal: True
find_similar_top_k: 10
find_similar_internal_targets:
  - n01613177_1321.JPEG
  - n01613177_1709.JPEG
  - n07897438_729.JPEG

result_category_map:
  0: n03767203 # WaterWheel
  1: n07897438 # Bottle
  2: n01613177 # Bird
  3: n04515003 # Piano
  4: n10247358 # Woman
  5: n02278980 # Butterfly
  6: n04583620 # Airplane
  7: n03877845 # Building
  8: n11669921 # Flower
  9: n01923025 # Insect